name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        build_type: [ Debug, Release ]
        c_compiler: [ gcc, clang, cl ]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            platform: windows
            generator: Ninja
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            platform: linux
            generator: ""
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            platform: linux
            generator: ""
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
            platform: macOS
            generator: ""
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: macos-latest
            c_compiler: gcc
          - os: macos-latest
            c_compiler: cl
          - os: ubuntu-latest
            c_compiler: cl

    steps:
      - uses: actions/checkout@v4

      - name: Setup GCC
        if: matrix.os == 'ubuntu-latest' && matrix.c_compiler == 'gcc'
        uses: Dup4/actions-setup-gcc@v1
        with:
          version: latest

      - name: Setup MSVC
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install ISPC
        uses: ispc/install-ispc-action@main
        with:
          platform: ${{ matrix.platform }}

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
          echo "build-tests-dir=${{ github.workspace }}/build/tests" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        shell: bash
        run: |
          generator_args=()
          if [ -n "${{ matrix.generator }}" ]; then
            generator_args+=(-G "${{ matrix.generator }}")
          fi
          cmake "${generator_args[@]}" \
            -B "${{ steps.strings.outputs.build-output-dir }}" \
            -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
            -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -S "${{ github.workspace }}" \
            -DENABLE_TESTS=ON

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }}

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-tests-dir }}
        run: ctest --output-on-failure
